# Generated by Django 2.2.14 on 2020-07-11 08:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('tags', '0002_auto_20200708_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('url_key', models.CharField(max_length=1000)),
                ('chapters', models.IntegerField(default=1)),
                ('dir_name', models.CharField(max_length=1000)),
                ('dir_abs_path', models.CharField(max_length=1200)),
                ('dir_media_path', models.CharField(max_length=1000)),
                ('cover_chapter', models.IntegerField(default=1)),
                ('cover_page', models.IntegerField(default=1)),
                ('cover_path', models.CharField(max_length=2400)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='entry creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='date last updated')),
                ('author', models.ManyToManyField(related_name='author', to='person.Person')),
                ('illustrator', models.ManyToManyField(related_name='illustrator', to='person.Person')),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('chapter', models.IntegerField(default=1)),
                ('read_left', models.BooleanField(default=True, verbose_name='read right to left?')),
                ('dir_name', models.CharField(max_length=1000)),
                ('dir_abs_path', models.CharField(max_length=2200)),
                ('dir_media_path', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='entry creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='date last updated')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=1)),
                ('file_name', models.CharField(max_length=200)),
                ('file_abs_path', models.CharField(max_length=2400)),
                ('file_media_path', models.CharField(max_length=2000)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Chapter')),
            ],
        ),
    ]
