# Generated by Django 2.2.14 on 2020-07-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_dir_last_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='dir_last_update_date',
        ),
        migrations.AddField(
            model_name='book',
            name='dir_update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='directory update date'),
        ),
    ]
