# Generated by Django 2.2.14 on 2020-07-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200711_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='dir_update_date',
        ),
        migrations.AddField(
            model_name='book',
            name='dir_update_timestamp',
            field=models.IntegerField(blank=True, null=True, verbose_name='directory update date'),
        ),
    ]
