# Generated by Django 2.2.14 on 2020-07-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200708_0704'),
        ('book', '0005_auto_20200711_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
