# Generated by Django 3.0.8 on 2020-07-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_chapter_illustrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='force_scan',
            field=models.BooleanField(default=False),
        ),
    ]
