# Generated by Django 3.0.8 on 2020-07-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20200716_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tag_tree',
            field=models.BinaryField(blank=True),
        ),
    ]
