# Generated by Django 3.0.8 on 2020-07-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20200716_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='tag_tree',
            field=models.BinaryField(blank=True),
        ),
    ]
