# Generated by Django 3.0.8 on 2020-07-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20200716_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('url_key', models.CharField(max_length=1000)),
                ('skip_scan', models.BooleanField(default=False)),
            ],
        ),
    ]
