# Generated by Django 2.2.14 on 2020-07-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
