# Generated by Django 3.0.8 on 2020-07-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200708_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_tree',
            field=models.BinaryField(blank=True),
        ),
    ]
