# Generated by Django 2.2.13 on 2020-07-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_auto_20200703_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='add_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date added'),
        ),
    ]
