# Generated by Django 2.2.13 on 2020-07-03 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_auto_20200703_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='add_date',
        ),
        migrations.AddField(
            model_name='manga',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='entry creation date'),
        ),
        migrations.AddField(
            model_name='manga',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date last updated'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
