# Generated by Django 2.2.13 on 2020-07-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_auto_20200703_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date last updated'),
        ),
    ]
