# Generated by Django 2.2.13 on 2020-07-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_auto_20200703_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
