# Generated by Django 2.2.13 on 2020-07-03 05:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0006_manga_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='pages',
        ),
        migrations.AddField(
            model_name='manga',
            name='chapters',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('chapter', models.IntegerField(default=1)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='date published')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='entry creation date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='date last updated')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manga.Manga')),
            ],
        ),
    ]
