# Generated by Django 2.2.13 on 2020-07-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_auto_20200703_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='folder_name',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
