# Generated by Django 2.2.13 on 2020-07-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0009_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='folder_path',
            new_name='abs_path',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='page_file',
            new_name='file_name',
        ),
        migrations.AddField(
            model_name='chapter',
            name='abs_path',
            field=models.CharField(default='', max_length=2200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='abs_path',
            field=models.CharField(default='', max_length=2400),
            preserve_default=False,
        ),
    ]
