# Generated by Django 2.2.13 on 2020-07-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0010_auto_20200704_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='abs_path',
            new_name='folder_path',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='abs_path',
            new_name='folder_path',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='abs_path',
            new_name='file_path',
        ),
    ]
