# Generated by Django 2.2.13 on 2020-07-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0011_auto_20200704_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='url_key',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
