# Generated by Django 2.2.13 on 2020-07-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0013_manga_cover_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='folder_name',
            new_name='dir_name',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='folder_path',
            new_name='dir_path',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='folder_name',
            new_name='dir_name',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='folder_path',
            new_name='dir_path',
        ),
    ]
