# Generated by Django 2.2.13 on 2020-07-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0014_auto_20200704_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='dir_path',
            new_name='dir_abs_path',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='dir_path',
            new_name='dir_abs_path',
        ),
    ]
