# Generated by Django 2.2.13 on 2020-07-04 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0015_auto_20200704_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='file_path',
            new_name='file_abs_path',
        ),
    ]
