# Generated by Django 2.2.13 on 2020-07-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0016_auto_20200704_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='file_media_path',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
