# Generated by Django 2.2.13 on 2020-07-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0017_page_file_media_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='dir_media_path',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manga',
            name='dir_media_path',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
