# Generated by Django 2.2.13 on 2020-07-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0018_auto_20200704_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='read_left',
            field=models.BooleanField(default=True, verbose_name='read right to left?'),
        ),
    ]
