# Generated by Django 2.2.13 on 2020-07-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0020_auto_20200705_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='cover_chapter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='manga',
            name='cover_page',
            field=models.IntegerField(default=1),
        ),
    ]
