# Generated by Django 2.2.14 on 2020-07-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('manga', '0022_manga_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='author',
        ),
        migrations.AddField(
            model_name='manga',
            name='author',
            field=models.ManyToManyField(related_name='author', to='person.Person'),
        ),
        migrations.RemoveField(
            model_name='manga',
            name='illustrator',
        ),
        migrations.AddField(
            model_name='manga',
            name='illustrator',
            field=models.ManyToManyField(related_name='illustrator', to='person.Person'),
        ),
    ]
